/*
 * InvisibleModal.java
 *
 * Created on December 1, 2008, 10:11 PM
 */

package uam;

/**
 *
 * @author  user
 */
public class InvisibleModal extends javax.swing.JDialog {
    
    public InvisibleModalThread thread;
    public static final boolean enabled = true;
    
    public static InvisibleModal create()
    {
        InvisibleModal result = new InvisibleModal(null,false);
        result.setSize(0, 0);
        return result;
    }
    public static InvisibleModal createAndShow()
    {
        InvisibleModal result = create();
        if(!enabled) return result;
        result.showInvisibleModal();
        return result;
    }
    public void hideInvisibleModal()
    {
        this.setVisible(false);
    }
    public void showInvisibleModal()
    {
        thread = new InvisibleModalThread(this);
        thread.start();
    }
    public static class InvisibleModalThread extends Thread
    {
        public InvisibleModal form;
        
        public InvisibleModalThread(InvisibleModal form)
        {
            this.form = form;
        }
        @Override public void run()
        {
            form.setVisible(true);
        }
    }

    /** Creates new form InvisibleModal */
    public InvisibleModal(java.awt.Frame parent, boolean modal) {
        super();
        //super(parent);
        initComponents();
        //setModal(modal);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setUndecorated(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InvisibleModal dialog = new InvisibleModal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
